#!/bin/bash

python run_fewselect_iter.py \
    --select_method=mixed \
    --select_iterations=4 \
    --select_sample_size=2 \
    --augment_sample_size=4 \
    --continual \
    --num_datasets=4 \
    # --disable_data_augmentation \
